name = "needforslots-net-pl"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=needforslots.net.pl"
HMAC_KEY = "f0744579e7a5225b05e25511a57374c9282777e73fc19cf405096ae59219c635"
COOKIE_NAME = "vvl"
PLAY_PATH = "try"
BUTTON_ID = "pe2fe9c8a931d55929c85cd17136a27ec"
GATE_SALT = "823e79adb678d9fd"
